remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

title: GoEcosystem Documentation
description: Organization-wide documentation and guidelines for GoEcosystem projects
show_downloads: false

# Enable GitHub Pages to render Markdown files
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - STYLE_GUIDE.md
  - ARCHITECTURE.md
