title: GoEcosystem Documentation
description: Documentation for the GoEcosystem Organization
theme: just-the-docs

aux_links:
  "GoEcosystem on GitHub":
    - "https://github.com/GoEcosystem"
    
heading_anchors: true

# Search settings
search_enabled: true

# Footer content
footer_content: "Copyright &copy; 2025 GoEcosystem. Distributed under the <a href=\"https://github.com/GoEcosystem/go-docs/blob/main/LICENSE\">MIT license.</a>"
