remote_theme: 
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

# Site configuration
title: GoEcosystem Documentation
description: Organization-wide documentation and guidelines for GoEcosystem projects
show_downloads: false
go_logo_enabled: true
show_hero: true
theme_mode: dark # or light

# GitHub repository
repository: GoEcosystem/go-docs

# Theme colors
theme_colors:
  primary: "#00ADD8"    # Go blue
  secondary: "#5DC9E2"  # Light blue
  accent: "#00FF41"     # Matrix green
  dark: "#0D1117"       # Near black
  darker: "#070A0F"     # Darkest background
  code_bg: "#1A1E26"    # Dark code background

# Navigation links
nav_links:
  - title: GoEcosystem Home
    url: https://goecosystem.github.io/
    icon: fa-home
  - title: Go Web Scraper
    url: https://goecosystem.github.io/go-web-scraper/
    icon: fa-spider
  - title: Go Cheatsheets
    url: https://goecosystem.github.io/go-cheatsheets/
    icon: fa-list-alt
  - title: GitHub
    url: https://github.com/GoEcosystem
    icon: fa-github

# Enable GitHub Pages to render Markdown files
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - STYLE_GUIDE.md
  - ARCHITECTURE.md
